
name: Continuous Integration

env:
  GO_VERSION: 1.21
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
         go-version: 1.21.x
         
    - name: Lint
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: latest
    - name: errors
      run: golangci-lint run
      if: ${{ failure() }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
